### ISSUE TITLE
Check if lock exists before adding / deleting events

### ISSUE THREAD

**Issue by kamigerami** [codelabsab/timereport-slack#100]
If lock exists - do not allow add or delete event

**Comment by parberge** [comment]
We need to rewrite `check_lock_state` method in action.py to use the new table etc that we created for locking.

**Comment by parberge** [comment]
I think this should wait for the outcome of #115 since I think we don't actually want/need to check every event if it's locked or not (read comments in #115)

**Comment by parberge** [comment]
@kamigerami @tommymalmqvist I believe we agree that we shouldn't lock on events anymore, so this can be closed?

**Comment by kamigerami** [comment]
but if a month is locked - we should still not be able to add events for that month ... I believe this ticket still is valid.

**Comment by parberge** [comment]
Ah yes. This should still be on hold though until we implemented the new way we lock. I don't think we have a concrete ticket on that but I believe @tommymalmqvist is doing something about it

**Comment by tommymalmqvist** [comment]
- [ ] implement get_lock method. Should use api v2 `read_lock` function.

**Comment by tommymalmqvist** [comment]
- [ ] Implemented lock check for delete action

**Comment by parberge** [comment]
Rolled out in release `1.11.0`

**Comment by parberge** [comment]
Rolled out in `1.12.0`
