### ISSUE TITLE
Unable to use lock when a month has no reported items

### ISSUE THREAD

**Issue by parberge** [codelabsab/timereport-slack#115]
If you have a month where you haven't added anything but still want to "sign off" the month it will result in:
`IndexError: list index out of range`
when executing:
`event = create_lock(user_id=self.user_id, event_date=self.params[1])`

**Comment by parberge** [comment]
By sign off I mean executing: `/timereport lock`

**Comment by parberge** [comment]
@tommymalmqvist and I discussed our implementation and if I remember correctly we said:
The lock key per event is unnecessary.
Each client (timereport-slack in this case) should just check the lock table and see if the month is locked or not. We don't need to lock individual events.

Do you agree with that @tommymalmqvist ?

**Comment by tommymalmqvist** [comment]
@parberge Yes, but this ticket will need some updates on timereport-api

**Comment by parberge** [comment]
@tommymalmqvist Would it be possible if you create that ticket in timereport-api and then we can reference that ticket from this one?

**Comment by tommymalmqvist** [comment]
@parberge already implemented in the [refactor-pynamodb](https://github.com/codelabsab/timereport-api/tree/refactor-pynamodb) in fact.

**Comment by parberge** [comment]
> @parberge already implemented in the [refactor-pynamodb](https://github.com/codelabsab/timereport-api/tree/refactor-pynamodb) in fact.

Ok, and refactor-pynamodb, what issue is that related to? Would be nice to link to it from here for others to follow

**Comment by kamigerami** [comment]
What is the actual task at hand here? Are we skipping the lock sequence or not? To lock on a month and not specific event does not solve the "unable to lock when a month has no reported items"

**Comment by tommymalmqvist** [comment]
> What is the actual task at hand here? Are we skipping the lock sequence or not? To lock on a month and not specific event does not solve the "unable to lock when a month has no reported items"

We should close this and refactor the locking function

**Comment by parberge** [comment]
@tommymalmqvist Maybe you can create a ticket with the appropriate action, and then link this issue to that one saying it will resolve this one. The bug is still valid until it's fixed 😄

**Comment by kamigerami** [comment]
looks to me like the locking function only locks for a month .. and not on a full date... example 2019-08 
https://github.com/codelabsab/timereport-slack/blob/225aa7d82213df8afdf66ff999eb928b32e3ed8c/chalicelib/action.py#L212

**Comment by parberge** [comment]
> looks to me like the locking function only locks for a month .. and not on a full date... example 2019-08
> https://github.com/codelabsab/timereport-slack/blob/225aa7d82213df8afdf66ff999eb928b32e3ed8c/chalicelib/action.py#L212

I believe that is what we agreed we wanted. I.e we should only lock on months

**Comment by kamigerami** [comment]
yes thus we should close ticket #116

**Comment by parberge** [comment]
@kamigerami no. We want to be able to lock a specific month. Not just the current month

**Comment by kamigerami** [comment]
What is the solution to this bug ? Can we define this exactly so that it is clear?

**Comment by parberge** [comment]
The current implementation creates a lock attribute in each event. The solution to this bug is to not do that and only care about if the date exists in our specific lock table. Something that I believe @tommymalmqvist is working on... (but not sure)

**Comment by tommymalmqvist** [comment]
The method `check_lock_state` in the class `Action` needs to be updated.

The following code checks lock state per event. This has been deprecated and we should use the lock function in api v2

```for event in json.loads(self._get_events(date_str=f"{self.date_start}:{self.date_end}")):
            if event.get("lock"):
                return True```

Check `_lock_action` for reference. We need to be able to get locks from backend.
