### ISSUE TITLE
Add possibility to lock a specific month

### ISSUE THREAD

**Issue by parberge** [codelabsab/timereport-slack#116]
When you execute `/timereport lock` it will lock the month that is the current month.

The user might want to lock a month that is in the past or is in the future.
This ticket should implement the support to enable that.

I think it can be an optional argument, i.e:
`/timereport lock`
Will lock the current month.

`/timereport lock 2019-01`
Will lock specified

The method class method `_lock_action` should be updated to also check for the optional argument (i.e the date string).
Today those arguments is stored in `self.params` attribute, so the method should check that and make sure it's a valid argument.

**Comment by kamigerami** [comment]
We should also be able to lock a month even if it does not have any entries ...

**Comment by parberge** [comment]
@kamigerami yes, we should not lock events at all actually. See the discussion in #115

**Comment by kamigerami** [comment]
this looks like it's already implemented

**Comment by kamigerami** [comment]
this should be closed since we already lock month?

**Comment by parberge** [comment]
I believe we can't lock for specific month with current implementation (tested with /timereport-dev lock 2019-09)

**Comment by kamigerami** [comment]
ok. 

So we need to define a clear action for this ticket. 

I.ex "To implement lock for any month we need to update lock.py with a new method that takes a full date etc etc ..... "  <-- obviously just made up.

**Comment by parberge** [comment]
@kamigerami Ok updated.

**Comment by kamigerami** [comment]
Closing this ticket as it already works.
