### ISSUE TITLE
Implement the edit action

### ISSUE THREAD

**Issue by parberge** [codelabsab/timereport-slack#12]
The value I see is from a pure user experience perspective:
Should `/timereport add today` work if it already has a value?
With `edit` we can make sure that the user tries to change something that already _exists_  which `/timereport add` doesn't. 

Actions:
Add code to edit action that only change a date if it already exist and also gives feedback to the user what changed in a nice way :)

**Comment by kamigerami** [comment]
not necessary anymore since we have "add" that will update if there is an entry already.

**Comment by parberge** [comment]
I think we might want to differentiate for a user experience. Can we
discuss this next session?

**Comment by kamigerami** [comment]
I think we should be able to edit everything up until it is locked.

**Comment by parberge** [comment]
Yes. This is more about how the user should change something. They can technically change with add. But the question is about the behavior and what the user expect to happen

**Comment by parberge** [comment]
@kamigerami @tommymalmqvist I've updated the description to make it more obvious what I mean.
What do you think?

**Comment by kamigerami** [comment]
what happens when you try to do timereport edit on something that does not exist? 

Can we do it the other way around? 

If you do `/timereport add intern_arbete 2019-10-20` on something that already exists... maybe you can get an interactive message saying `"vab 2019-10-20 entry already exists ... do you want to change from vab -> intern_arbete 2019-10-20` yes / no ?

**Comment by parberge** [comment]
@kamigerami Sure, that would also be a nice feature. But as a user does it feel natural to call `/timereport add` when you want to change something that you know already exists?

We already have boilerplate (i.e we have /timereport edit  today), so adding support for this shouldn't be to hard.

**Comment by kamigerami** [comment]
Ok. Fair enough

**Comment by parberge** [comment]
Rolled out in `1.13.0`
