### ISSUE TITLE
Move code for route /interactive from app.py

### ISSUE THREAD

**Issue by tommymalmqvist** [codelabsab/timereport-slack#125]
We need to clean up the code for /interactive route in app.py

app.py should preferably just pass the Chalice app to the proper function for handling

The interactive sessions only contains 2 states that can impact the program logic: `submit type` and `action`.

submit type: `submit_yes` or `submit_no`
action: `add` or `delete`

- [ ] handle request
- [ ] handle states of submit type
- [ ] handle states of action type

We will also need to implement functions that prepares data for calling our api lib that will be created in #127 
- [ ] create_event
- [ ] read_event
- [ ] delete_event
- [ ] create_lock
- [ ] read_lock

**Comment by tommymalmqvist** [comment]
app.py should only contain:
```
@app.route('/interactive', method='POST', content_types=['application/x-www-form-urlencoded'])
def interactive():
    return interactive_handler(app)
```

**Comment by parberge** [comment]
`interactive_handler` is that going to be a function that does all that thing it does today in /interacive ?

**Comment by tommymalmqvist** [comment]
Depends on #127

**Comment by tommymalmqvist** [comment]
- [ ] Rebase on master

**Comment by parberge** [comment]
#168 will resolve this issue in another way. Can we close this if #168 is merged @tommymalmqvist ?

**Comment by parberge** [comment]
I guess the part of migrating to the new API is still relevant. Maybe we can update the ticket to only that part?

**Comment by parberge** [comment]
> I guess the part of migrating to the new API is still relevant. Maybe we can update the ticket to only that part?

@tommymalmqvist Bump.

**Comment by tommymalmqvist** [comment]
Closing this
