### ISSUE TITLE
Remove slackclient

### ISSUE THREAD

**Issue by parberge** [codelabsab/timereport-slack#126]
In various tickets (#109, #110) I introduced slackclient because I believed it would help us.
After some trail and error I found out that it doesn't work for us because it doesn't support the `response_url` that we use.

Actions:
- [x] remove slackclient
- [x] Add methods to Slack class to send messages using requests instead

**Comment by kamigerami** [comment]
This is a ticket with a clearly defined action and solution specified. I think somebody can pick this up at anytime and do the work as long as you stick to the scope of removing slackclient and replacing with methods using requests.

**Comment by kamigerami** [comment]
close this?

**Comment by parberge** [comment]
I want to deploy to prod before closing

Den tors 24 okt. 2019 17:10Kami Gerami <notifications@github.com> skrev:

**Comment by parberge** [comment]
Fixed in release `1.10.2`
