### ISSUE TITLE
Upgrade to python 3.7

### ISSUE THREAD

**Issue by parberge** [codelabsab/timereport-slack#129]
aws lambda supports python 3.7 (https://aws.amazon.com/about-aws/whats-new/2018/11/aws-lambda-supports-python-37/)

We should upgrade to get the benefits (https://docs.python.org/3/whatsnew/3.7.html).

I'm uncertain on how to do that. Need to update the description when I know.
Actions:
- [x] update Pipfile to say python 3.7
- [x] update .travis to use python 3.7
- [x] update chalice to use python 3.7

**Comment by kamigerami** [comment]
Yes we just need to update the project to use 3.7 and aws + chalice will do just that.

**Comment by parberge** [comment]
Rolled out in `1.13.3`
