### ISSUE TITLE
Always deploy to prod when push/merge to master

### ISSUE THREAD

**Issue by parberge** [codelabsab/timereport-slack#143]
Today we require a tag on master branch to deploy to production. This is no longer necessary.
We should remove that requirement.

Also some other things to consider:
* Always deploy to dev (even for master branch); Otherwise in case we push to master branch production will be updated but not dev
* Prevent travis from running on PR changes (since this is redundant)

**Comment by kamigerami** [comment]
What are the suggestions for dev vs prod?

- Always deploy to dev on any branch?
- Always deploy to dev + prod on master branch?

**Comment by parberge** [comment]
> What are the suggestions for dev vs prod?
> 
> * Always deploy to dev on any branch?
> * Always deploy to dev + prod on master branch?

Yes.
