### ISSUE TITLE
Get notification/alarm when runtime error happens

### ISSUE THREAD

**Issue by parberge** [codelabsab/timereport-slack#18]
It be good if we would get notified if for instance an exception happens that we don't catch.

Actions:
Find out if this is possible and create a ticket o implement it if it makes sense

**Comment by kamigerami** [comment]
this should be added as a slack response method in the code

**Comment by parberge** [comment]
@kamigerami I rewrote the ticket a bit. Please check title and description if you agree

**Comment by kamigerami** [comment]
Ok. So this ticket is more about research and create a new ticket in the future about it...

**Comment by mattiaslundberg** [comment]
The solutions that comes to mind:
* Set up our own alerts from cloudwatch-logs: https://medium.com/pixelpoint/how-to-send-aws-cloudwatch-alarms-to-slack-502bcf106047
* Use a dedicated service, for example Sentry: https://sentry.io/for/pythonawslambda/ ($26/month if we don't want to use a shared account)

Setting up our own handling would work and is cheaper (only cost for lambda over current cost). The disadvantage is that it is more likely to break and we have no way of knowing...

**Comment by parberge** [comment]
I have no experience with sentry but I've heard good things about it.
So for me personally I would love to use Sentry.

Since it's a cost involved I guess it's up to @tommymalmqvist or @kamigerami though

**Comment by kamigerami** [comment]
Can we try sentry on a free trial or something to evaluate against aws cloudwatch / slack alerting?

**Comment by parberge** [comment]
@kamigerami Maybe you can sign up and see:
https://sentry.io/signup/

**Comment by parberge** [comment]
See #188
