### ISSUE TITLE
Add the possibility to see how many work hours there is for a given month

### ISSUE THREAD

**Issue by parberge** [codelabsab/timereport-slack#33]
Would be nice if the number of hours in a month could be provided.
I don't know in what context though?

Maybe for `list` action?

**Comment by kamigerami** [comment]
why would we need this?

**Comment by parberge** [comment]
Would be nice to get the number of hours worked for a given month since
it's quite usual that you need to provide this to someone

**Comment by kamigerami** [comment]
maybe we could use something like :
https://calendarific.com/

**Comment by parberge** [comment]
Worth a try.

Make sure our service can handle that the it doesn't respond and take an appropriate action

**Comment by kamigerami** [comment]
maybe https://developers.google.com/calendar/quickstart/python

**Comment by kamigerami** [comment]
we have this in timereport-UI now and the data is available at api.codelabs.se
will implement this for list action

**Comment by parberge** [comment]
@kamigerami @tommymalmqvist I think having this in the timereport-ui is good enough.
Should we close this?
