### ISSUE TITLE
Add possibility to sign off a timereport

### ISSUE THREAD

**Issue by parberge** [codelabsab/timereport-slack#34]
Would be nice if it was possible to sign-off a timereport.
Some of the expected features:
* It would default for a whole month (but should support signing off days and weeks as well)
* A signed off time is read only. I.e to edit one would need to run a unlock or something
* A way to only retrieve signed-off report (/timereport list 2019-01-01 signed-off). So that the person getting the report knows if it's ready or not

**Comment by parberge** [comment]
A bonus would also some kind of reminder end of the month that it's time to sign off a report

**Comment by kamigerami** [comment]
how would this be implemented? Do we add another attribute in the database for "signed-off" ? We don't allow update or insert to the db if it has this flag?

**Comment by parberge** [comment]
I don't know dynamodb that well. Can you protect a key from being updated?
Or do we need to handle this lock via the API by implementing this logic
ourselves

**Comment by kamigerami** [comment]
yes we need to dig and find the information on how to do this

**Comment by parberge** [comment]
Maybe one solution (as discussed briefly on slack):
Add a key/value to each entry in datebase, e.g "locked" with value True/False.

Add logic to `add` and `delete` action that it can't change an entry that has "locked": True.

Also implement `/timereport sign-off` (or lock) that locks a timereport.

**Comment by parberge** [comment]
Depends on: https://github.com/codelabsab/timereport-api/issues/13

**Comment by parberge** [comment]
The plan to solve this is:
In the `_lock_action` method it should:
1. Fetch the events
2. Add the key `lock` and set it to `true`
3. Send the updated event to the `_add_action`

**Comment by parberge** [comment]
So the plan has changed a bit.
Now we want this approach:
1. create a separate lock document that locks for a month
2. Update the functions timereport-slack to lookup in this document for various actions

**Comment by kamigerami** [comment]
solved in release https://github.com/codelabsab/timereport-slack/commit/8c9a3aab071b0719d85e9ce6fe0f253d79045c95
