### ISSUE TITLE
delete action - verify successful vs unsuccessful delete before returning OK

### ISSUE THREAD

**Issue by kamigerami** [codelabsab/timereport-slack#53]
currently we always return that the delete was successfull but we need to verify this by checking if the entry exists or not.

**Comment by parberge** [comment]
@kamigerami A change in backend is necessary for this right?

**Comment by parberge** [comment]
@kamigerami Any input on my question?
We check if status != 200 of the delete API call, but you say that timereport-api will always respond with 200?

**Comment by kamigerami** [comment]
will have to verify ...

**Comment by tommymalmqvist** [comment]
Not handled yet 

https://github.com/codelabsab/timereport-api/blob/8c939a78ee475d9f7d619d12b6ae56bcb3593d23/chalicelib/lib/db_v1.py#L55

**Comment by parberge** [comment]
@tommymalmqvist So this ticket is blocked by the fact that timereport-api always will respond 200 and never provide any message saying that delete didn't work?

**Comment by parberge** [comment]
I see two solutions:
1. The clients need to check if the event exist before trying to delete.
2. The API will return data about the operation (i.e that no events was deleted or something).

I would prefer option 2.
