### ISSUE TITLE
Refactor app.py

### ISSUE THREAD

**Issue by parberge** [codelabsab/timereport-slack#54]
In my opinion we have too much logic inside `app.py`.

I would prefer some kind of abstraction of this by maybe the use of a class or something.
Ofc ordinary functions works as well.

**Comment by parberge** [comment]
In my head `index():` could probably look something like this:

```
def index():
    slack_request = app.current_request.raw_body.decode()
    slack_event = Event(slack_request)
    slack_event.validate_action()
    slack_event.perform_action()
    return ''
```

**Comment by parberge** [comment]
I think we should discuss this in next session @kamigerami @tommymalmqvist

**Comment by parberge** [comment]
Maybe we should start with a class to only handle the abstraction of actions.
Something like this:

```
def index():
    req = app.current_request.raw_body.decode()
    payload = slack_payload_extractor(req)

    action = Action(payload)

    # Validate that the intended action (add, list etc) has correct input values etc
    action.validate()

    # Check if confirmation is required and send it
    action.send_confirmation()

    #
    if action.is_confirmed():
        action.commit()

    return ''
```

**Comment by kamigerami** [comment]
sure

**Comment by parberge** [comment]
I think @tommymalmqvist has some thoughts and suggestion about this?
Also lets consider #81 .

**Comment by parberge** [comment]
Maybe we should close this actually. The scope has changed a bit. It's only the "interactive" route in app.py that has too much logic right now.

**Comment by tommymalmqvist** [comment]
Closing this. Ticket for refactoring /interactive should be opened instead.
