### ISSUE TITLE
Make the list action format better

### ISSUE THREAD

**Issue by parberge** [codelabsab/timereport-slack#56]
Would be nice if the format of the output was a bit more pretty.

We could leverage `attachment` do to that I believe:
https://api.slack.com/docs/message-guidelines

**Comment by parberge** [comment]
Actually this is the more appropriate guide line:
https://api.slack.com/messaging/composing/layouts

**Comment by parberge** [comment]
Looked more into this. It seems like the supported formats doesn't suit our output.

We could build a table ourselves with pandas or prettytable. Just need to check which has the least inpact on size vs benefits 😄

**Comment by parberge** [comment]
The suggested output (discussed on slack) that we want to present:
![image](https://user-images.githubusercontent.com/5441497/64988731-6b802900-d8cc-11e9-91df-67f8a3530dea.png)

**Comment by parberge** [comment]
This ticket should wait for #109 since it will make this ticket easier to do

**Comment by tommymalmqvist** [comment]
Use slack blocks?

**Comment by kamigerami** [comment]
Maybe something like this: 

<img width="697" alt="Screen Shot 2019-10-20 at 11 32 15" src="https://user-images.githubusercontent.com/9321510/67157505-582e0680-f32d-11e9-86cc-6f34dcc5963e.png">


`[
	{
		"type": "section",
		"text": {
			"type": "mrkdwn",
			"text": "Reported time for period *2019-10-01:2019-10-31*"
		}
	},
	{
		"type": "divider"
	},
	{
		"type": "section",
		"text": {
			"type": "mrkdwn",
			"text": "Date: *2019-10-01*\nReason: *vab*\nHours: *8*"
		}
	},
	{
		"type": "context",
		"elements": [
			{
				"type": "plain_text",
				"text": "Locked:"
			},
			{
				"type": "plain_text",
				"emoji": true,
				"text": ":lock:"
			}
		]
	},
	{
		"type": "divider"
	},
	{
		"type": "section",
		"text": {
			"type": "mrkdwn",
			"text": "Date: *2019-10-02*\nReason: *intern_arbete*\nHours: *8*"
		}
	},
	{
		"type": "context",
		"elements": [
			{
				"type": "plain_text",
				"text": "Locked:"
			},
			{
				"type": "plain_text",
				"emoji": true,
				"text": ":lock:"
			}
		]
	},
	{
		"type": "divider"
	},
	{
		"type": "section",
		"text": {
			"type": "mrkdwn",
			"text": "Date: *2019-10-03*\nReason: *semester*\nHours: *8*"
		}
	},
	{
		"type": "context",
		"elements": [
			{
				"type": "plain_text",
				"text": "Locked:"
			},
			{
				"type": "plain_text",
				"emoji": true,
				"text": ":lock:"
			}
		]
	},
	{
		"type": "divider"
	}
]`

**Comment by parberge** [comment]
Yes we have a ticket to use slack blocks already. But that also require changing the way we send attachment etc #111
