### ISSUE TITLE
Refactor json_factory

### ISSUE THREAD

**Issue by parberge** [codelabsab/timereport-slack#58]
The function name `json_factory` suggests that it expects json as input (which it doesn't).

To make it more obvious we should refactor the name. Maybe make the `factory` a function that can handle both cases?

**Comment by tommymalmqvist** [comment]
The event class should have a method that returns the object in json

**Comment by parberge** [comment]
@tommymalmqvist What class are we talking about? Or are you referring to a class you intend to create?

**Comment by tommymalmqvist** [comment]
There’s really only one case.

In /command we only have to check that the range is correct. There’s no reason to create events in that part of the session.

When we get a yes from /interactive is the only time we have to create events

**Comment by tommymalmqvist** [comment]
We should remove factory and rename json_factory to factory.

In /command we should only validate that the date or date range is correct.

We should then create one dict and send to the client instead of a list of dicts like we do now

**Comment by tommymalmqvist** [comment]
This is what we get with the current setup



                'fields': [
                    {
                        'title': 'User',
                        'value': 'par.berge',
                        'short': False
                    }, {
                        'title': 'Type',
                        'value': 'vab',
                        'short': False
                    }, {
                        'title': 'Date start',
                        'value': '2019-09-28',
                        'short': False
                    }, {
                        'title': 'Date end',
                        'value': '2019-09-28',
                        'short': False
                    }, {
                        'title': 'Hours',
                        'value': '8',
                        'short': False
                    }
                ],

**Comment by parberge** [comment]
@tommymalmqvist feel free to update the description to make it more obvious if you like.

**Comment by tommymalmqvist** [comment]
Closing. Will open new.
