### ISSUE TITLE
refactor: to use eafp principle instead of if else

### ISSUE THREAD

**Issue by kamigerami** [codelabsab/timereport-slack#75]
We should move away from all the if else statements and try to use something different.

maybe : https://stackoverflow.com/questions/11360858/what-is-the-eafp-principle-in-python

**Comment by parberge** [comment]
Sure. Maybe we should open a ticket with concrete action?

"Refactor condition checks in X" or something.
Now this ticket is more of a general question. hard to do something concrete.

**Comment by parberge** [comment]
What do you think @kamigerami ?

**Comment by tommymalmqvist** [comment]
Low priority and too broad, we should close this.
