### ISSUE TITLE
Add a summary for list action

### ISSUE THREAD

**Issue by kamigerami** [codelabsab/timereport-slack#76]
So basically we can just list for a month.

/timereport list 2019 02

will give you everything for that month

and if you want to know the total of everything (summary)
you will query 
/timereport list total 2019 02
```{'antal_arbetstimmar': 160, 'avvikelse_timmar': 37, 'fakturerbara_timmar': 123}```

**Comment by parberge** [comment]
I think we should wait for PR #74 before we decide anything right. We might even decide that the "synax" should change

**Comment by parberge** [comment]
Also #33

**Comment by kamigerami** [comment]
agreed

**Comment by parberge** [comment]
@kamigerami What's the status on this ticket? In #33 you commented that this is implemented in the frontend. Are we going to do it the same way? PR #74 got closed by you without merging.

I would prefer to have this "summary" for all our list actions (maybe not for a single date/today keyword)

**Comment by parberge** [comment]
@kamigerami Do we still want to have a summary in slack? I think if you want to have summary you could go to the timereport UI instead. What do you think?

**Comment by kamigerami** [comment]
I think we should have it in the CLIENT as well

/timereport summary month

**Comment by parberge** [comment]
@kamigerami Hehe sorry for being such a pain in the ass, but you as author of ticket shouldn't decide that the "needs_verification" can be removed 😄 

I actually don't think this logic is necessary to add to our slack client. My vote is to close.

If the others agree that this is something we want I won't object. My only suggestion in that case is not to introduce another commad (i.e `/timereport summary`), just add the data to the `/timereport list` output.

**Comment by kamigerami** [comment]
sure .. or can we introduce the logic in the api instead? something that will basically do:
/api/summary/<YYYY-MM>
and do: 
how many work days is it this month?
how many entries do we have for this month for this user?
return summary "total work days minus entries for user"

**Comment by parberge** [comment]
Yeah I don't know. I think we decided not to add this into the backend API because we want it to be as simple as possible. 

So I think endpoints in backend API to assist in doing this could be added. Maybe an endpoint to get data about the working days for a month or something to make it easier at least. What do @tommymalmqvist @stefan-julin and @marresgit think?

**Comment by kamigerami** [comment]
We do have data of working days. Located at timereport.codelabs.se/<YYYY-M>.json

**Comment by parberge** [comment]
Decided together that this is not applicable right now
