### ISSUE TITLE
Evaluate to use python black (automatic formatter)

### ISSUE THREAD

**Issue by parberge** [codelabsab/timereport-slack#78]
Instead of rely on linting to report "bad code style" we could leverage this tool:
https://github.com/ambv/black

vs code python extension has support for this natively

**Comment by kamigerami** [comment]
don't we have something in pycharm or our IDE instead of a CLI tool ?

**Comment by parberge** [comment]
@kamigerami That's the point. This tool will be used automatically by for example VS code:
https://code.visualstudio.com/docs/python/editing#_formatting

**Comment by parberge** [comment]
Reading more about it a formatter doesn't really replace linting. It's complementary:
"Although there is a little overlap between formatting and linting, the two capabilities are complementary."

**Comment by parberge** [comment]
Ok so this is more up to each users and is not something to "solve" in a ticket.
A more concrete ticket would be to standardise what format to follow.
And to enforce that format is to probably use a linter in the pipeline.
