### ISSUE TITLE
Create class for messages

### ISSUE THREAD

**Issue by parberge** [codelabsab/timereport-slack#81]
In `app.py` and in `Action` class we have quite a lot of code for sending various slack messages.

I think we should create a class for this.
Relates to #54

**Comment by kamigerami** [comment]
are we talking about `slack_responder(self.response_url, f'```{str(r)}```')`

**Comment by parberge** [comment]
We do stuff like:
```
 slack_client_response = slack_client_responder(
            token=self.slack_token,
            user_id=self.user_id,
            attachment=attachment
        )

        if slack_client_response.status_code != 200:
            log.error(
                f"""Failed to send response to slack. Status code was: {slack_client_response.status_code}.
                The response from slack was: {slack_client_response.text}"""
            )
            return "Slack response to user failed"
        else:
            log.debug(f"Slack client response was: {slack_client_response.text}")

```
in the `Action` class.
And in app.py we have stuff for interactive message.
I think a class to abstract these makes sense. This would be the final part of #54 
What do you think @kamigerami @tommymalmqvist

**Comment by parberge** [comment]
So I think something in app.py for '/interactive' route:

```
message = Message(payload)
message.send_message()
```

But that would require a lot of logic builtin into the class itself.
Maybe a better approach is to use a message class or something within `Action` class since it knows what type of action it is etc.

**Comment by parberge** [comment]
Since we might be rewriting how we communicate with slack (see #109, #110, #111) this section of app.py might be made more simple. I think we can hold this one for now and check back later when those are done

**Comment by parberge** [comment]
I believe @tommymalmqvist is reworking this already. Will close this ticket
