### ISSUE TITLE
Solve deprecation warning

### ISSUE THREAD

**Issue by parberge** [codelabsab/timereport-slack#82]
We use `import botocore.vendored.requests.api as requests` which will give you the following message when using the `post()` method:

```
DeprecationWarning: You are using the post() function from 'botocore.vendored.requests'.  
This is not a public API in botocore and will be removed in the future. 
Additionally, this version of requests is out of date. 
We recommend you install the requests package, 'import requests' directly, and use the requests.post() function instead.
    DeprecationWarning
```

We should instead use the ordinary requests (which needs to be added to requirements.txt` as well

**Comment by kamigerami** [comment]
Action: Change from botocore requests to requests.

**Comment by parberge** [comment]
@kamigerami Thanks I updated the description to make it more clear

**Comment by parberge** [comment]
Rolled out in release `1.10.1`
