### ISSUE TITLE
Add possiblity to list for specific month

### ISSUE THREAD

**Issue by parberge** [codelabsab/timereport-slack#96]
It would be nice if it was possible to list the timereport for the specified month.

It's ofc possible today with time range (i.e `timereport list 2019-01-01:2019-01-31`), but I think it should be easier.

I would prefer:
`/timereport list january (or jan)`. 

Or maybe `/timereport list` (without args) should list for the given month?

**Comment by kamigerami** [comment]
and Also - default to current month when you list.

today running list will list everything since the beginning of time.

**Comment by parberge** [comment]
As discussed during hackaton 2019-08-30, we won't support human language definition of dates (i.e jan/january)

**Comment by parberge** [comment]
> and Also - default to current month when you list.
> 
> today running list will list everything since the beginning of time.

In release `1.8.0` this is now the default behaviour

**Comment by parberge** [comment]
Fixed in `1.9.0`
