### ISSUE TITLE
Add but skip / remove weekends and red days

### ISSUE THREAD

**Issue by kamigerami** [codelabsab/timereport-slack#98]
When we add something to timereport. We usually add some entries from start_date:end_date however the loop does not take in to consideration that the particular day is a red day or a weekend. We should add a warning when such days are added ... 

something like "are you sure you want to add <type> (intern_arbete) to date 2019-06-30. It is a weekend. 

All these dates are skewing and making the "total hours for the month" wrong in the end. which takes a lot of manual work to verify if the date is a weekend or a redday.

**Comment by parberge** [comment]
Since we don't have summary in slack yet this is not really applicable yet.

I guess if we had a summary it could be nice to have a summary value that excludes weekends and holidays.

But honestly it feels quite painful to add this just to get a better summary? I think it's not worth the effort.

My vote is not do implement this

**Comment by kamigerami** [comment]
as an admin user that only can look at timereports through the frontend UI I think this feature is very important - we do have a summary implemented in the frontend for example. 

An example of how skewed the hours are is if you look at your entry for the month of July. 
<img width="363" alt="Screenshot 2019-08-31 at 17 49 07" src="https://user-images.githubusercontent.com/9321510/64066279-e6ccb400-cc17-11e9-9676-ed1667981ee9.png">

**Comment by kamigerami** [comment]
@tommymalmqvist @parberge

**Comment by parberge** [comment]
@kamigerami I don't understand why this is relevant to timereport-slack?

**Comment by kamigerami** [comment]
could be... should the api backend skip adding entries to the backend if its a weekend? so lets say client posts range.. the backend loops through these dates and looks for if it is a weekend?

**Comment by parberge** [comment]
Something like that. If that is to much logic maybe we can have an endpoint for checking if workday and then every client can use that

**Comment by parberge** [comment]
But honestly since this is only summary and only exists in frontend UI I think this logic shouldn't be added. The frontend can exclude non workdays when calculating total hours  and the hours reported. Even if the hours reported are on non workdays it can just skip counting that day

**Comment by kamigerami** [comment]
Implemented in UI in commit : https://github.com/codelabsab/timereport-ui/commit/5a2c9e777b2a38a2b00aace2ff87fc95ef2c1efc

**Comment by kamigerami** [comment]
before:
<img width="363" alt="Screenshot 2019-08-31 at 17 49 07" src="https://user-images.githubusercontent.com/9321510/64078211-03302580-ccd8-11e9-88ad-c4249f83664f.png">

after:
<img width="364" alt="Screenshot 2019-09-01 at 16 45 45" src="https://user-images.githubusercontent.com/9321510/64078207-fb708100-ccd7-11e9-9e0e-9745b1a60fed.png">

**Comment by kamigerami** [comment]
hmm looks wrong

**Comment by parberge** [comment]
@kamigerami I think this ticket should be moved to timereport-ui?

**Comment by kamigerami** [comment]
yes. closing this.
